CREATE TABLE SONGS (
song_id    STRING,
song_length BIGINT,
genre_ids STRING,
artist_name STRING,
composer STRING,
lyricist STRING,
language STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/tmp/songs1.csv' INTO TABLE SONGS;



CREATE TABLE SONG_INFO(
song_id    STRING,
name STRING,
ISRC STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/tmp/song_extra_info.csv' INTO TABLE SONG_INFO;


CREATE TABLE order_detail(
`name` STRING,
`date` STRING,
item STRING,
price int,
quantity int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/tmp/order.csv' INTO TABLE order_detail;